name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: 52.66.115.98
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            mkdir week-25
            cd week-25
            git pull
            npm i
            npm run build
            npm run start