name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: 52.66.115.98
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            if [ ! -d "COHORT3.0-DEVOPS-WEEK-25" ]; then
              git clone https://github.com/IamAshishSingh02/COHORT3.0-DEVOPS-WEEK-25.git
            fi

            cd COHORT3.0-DEVOPS-WEEK-25
            git pull

            if ! command -v npm &> /dev/null
            then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            npm install
            npm run build
            npm run start